### PR TITLE
Feature/fix docker errors and refactor login component styles

### PR DESCRIPTION
**Pull request by akilah-littlejohn**

### CODE REVIEW

**Comment by sforsyth089** [comment]
Sorry for delay, we are confirming this !

**Comment by sforsyth089** [comment]
Hello - Can you provide more details/reasoning behind the recommended updates?  Then we'll be happy to review from there for the merge request. @wisdomkeeper

**Comment by akilah-littlejohn** [comment]
I was getting this error when trying to build docker image, "Job name “..getProjectMetadata” does not exist"
Most of my research suggested that it means that angular needed an upgrade, So I upgraded using these steps (https://youtu.be/SHt-YBt95qk) to ensure that the upgrades wouldn't break the app.
https://stackoverflow.com/questions/60174503/job-name-getprojectmetadata-does-not-exist
2021-02-08 (1)_LI (1)
The only other thing I did was disabled ivy (the compiler that comes with Angular version 9+) because it wasnt compatible with carbon library

**Comment by amfred** [comment]
We need a UI code reviewer...

**Comment by Mromany** [comment]
in package.json file some confliect lib will make this issye then you must change this package with old one

**Comment by Mromany** [comment]
try https://stackoverflow.com/a/62564184 and https://stackoverflow.com/a/60207420

**Comment by akilah-littlejohn** [comment]
These are screenshots of why I made version changes I do believe I fix those error messages

**Pull request closed without merging**
