### PR TITLE
Initial Changes to support appi-id authentication

### PR DESCRIPTION
**Pull request by yochanah**

### CODE REVIEW

**Comment by upkarlidder** [comment]
Great. Thanks @yochanah. Looking into this right now.

**Comment by upkarlidder** [comment]
The App ID service was missing the redirect URL. I added that. The widget comes up now and I am able to log in using google and email/password. We will take it out in production.

image


The code is still not hooked up with routing etc. I am investigating as well.

**Comment by RickPoleshuck** [comment]
Is it possible to commit all the files required to build with your new authentication? If not can you put the directions on how to create the missing file in the README?

This is the error I get when building:

ERROR in src/app/services/authentication.service.ts:7:52 - error TS2307: Cannot find module '../configurations/oidcAuthenticationConfiguration'.

**Comment by upkarlidder** [comment]
@RickPoleshuck, the current code uses `oidcAuthenticationConfiguration`, which in turn uses the `IBM Security Verify` service. You have to 
- create the service
- add a custom application
- grab the creds and add to `oidcAuthenticationConfiguration` file

The service is hard to configure and also expires in 30 days of free use.

This PR moves off of the `IBM Security Verify` service and to the `IBM App Id` service, which in my opinion, is a lot simpler to use. @yochanah was changing the code to remove dependency on OIDC stuff and add code to work with the App ID. This work will take a few more days. You are welcome to checkout this PR and help with the code. I am also happy to pair program on this if the group is interested. 

Some links if you are interested in learning more:
- https://www.ibm.com/cloud/blog/secure-your-single-page-angular-apps-using-app-id
- https://cloud.ibm.com/docs/appid?topic=appid-tokens
- https://cloud.ibm.com/docs/appid?topic=appid-single-page&interface=ui
- working sample - https://github.com/ibm-cloud-security/appid-clientsdk-js/tree/master/sample

Related to #42

**Review by upkarlidder — APPROVED** [review]
Looks good. Thank you @yochanah

**Pull request merged**
