### PR TITLE
Extract case charges outside of modal component #93

### PR DESCRIPTION
**Pull request by nikuzejl**
Instead of having the list of charges in the modal component, it was moved to a utility class. The modal component gets the list of charges from that utility class

### CODE REVIEW

**Review by upkarlidder — APPROVED** [review]
Looks good to me. @wisdomkeeper pls also review.

**Review by w-alvarez — CHANGES_REQUESTED** [review]
I think this PR should be edited to not commit the package-lock.json so we don't have 21k lines added

**Comment by nikuzejl** [comment]
Previous changes to the package-lock.json file have been reverted

**Comment by upkarlidder** [comment]
@wisdomkeeper can you please review when you get a chance? Thank you.

**Pull request merged**
