### PR TITLE
 ng test fails #45 

### PR DESCRIPTION
**Pull request by tumit**

### CODE REVIEW

**Comment by upkarlidder** [comment]
Thank you @tumit! 

@wisdomkeeper pls provide feedback when you get a chance.

**Review by akilah-littlejohn — DISMISSED** [review]
There is a commit that needs to be signed off correctly, https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/pull/81/checks?check_run_id=3862077076

**Comment by upkarlidder** [comment]
Thank you @wisdomkeeper. @tumit, can you please fix the DCO check as explained in the link.

https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/pull/81/checks?check_run_id=3862077076

**Comment by tumit** [comment]
Done but I'm no sure I do it correctly. Please check again thanks :)

**Comment by demilolu** [comment]
@tumit looks like it didn't work. @upkarlidder do you have any advice here on DCO?

**Review by demilolu — APPROVED** [review]

**Comment by demilolu** [comment]
@tumit Thanks again for your contribution to our projects! We would like to invite you to join us for our Hacktoberfest Demo Day on October 29th where we'll be highlighting contributions and thanking everyone who participated. Let me know if you can make it! https://www.crowdcast.io/e/hacktoberfest-demo-day/register

**Pull request merged**
